# theme basic info
theme_info:
  name: ILS
  version: 1.1.1
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils

# favicon
favicon: images/favicon.png

# avatar
avatar: images/avatar.png

# navigation menu
menu:
  主页: /
  归档: /archives
  # 分类: /category
  # 标签: /tag
  链接: /links
  关于: /about
  # ...

# RSS
rss:
  enable: true

# comment plugin
comments:
  # Valine https://github.com/xCss/Valine
  valine:
    enable: true
    appid: 7pPhwqK3blQJSznIgu7jRJWI-gzGzoHsz               # your leancloud application appid
    appkey: Oz9ktEWXHxxXWg6h7Va0zX57              # your leancloud application appkey
    meta: ['nick','mail','link']                # comment input meta, type: Array, values: ['nick','mail','link']
    placeholder: 请提出您的宝贵建议~          # your placeholder

  # Gitalk https://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id:             # GitHub repo owner
      repository:          # Repository name to store issues
    client_id:             # GitHub Application Client ID
    client_secret:         # GitHub Application Client Secret

# website count
website_count:
  # busuanzi http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: false
    site_pv: true
    page_pv: true

# Local Search
# Dependencies: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true

  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto  # values: auto | manual

  # Unescape html strings to the readable one.
  unescape: false

  # Preload the search data when the page loads.
  preload: false

# Code Copy
code_copy:
  enable: true
  style: flat  # values: default | flat | mac

# sidebar tools
side_tools:
  enable: true
  position: right  # values: left | right

# back to top
back2top:
  enable: true
  position: left  # values: left | right

# Table of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

# magic theme
magic:
  enable: true
  transform: true
  sidebar:
    enable: true
    fixed: true
    position: left  # values: left | right